-- 1. Create Global App Settings Table
create table if not exists public.app_settings (
  id int primary key generated by default as identity,
  premium_mode_enabled boolean default false, -- Default is Freemium (False)
  updated_at timestamptz default now()
);

-- Insert default row if not exists (Singleton pattern logic)
insert into public.app_settings (id, premium_mode_enabled)
values (1, false)
on conflict (id) do nothing;

-- RLS for App Settings
alter table public.app_settings enable row level security;
create policy "Public read settings" on public.app_settings for select using (true); -- Everyone needs to know the mode
create policy "Admins update settings" on public.app_settings for update using (
  exists (select 1 from public.users where id = auth.uid() and role = 'admin')
);

-- 2. Add Suspension Column to Users
alter table public.users add column if not exists is_suspended boolean default false;


-- 3. RPC: Toggle Global Premium Mode
create or replace function admin_toggle_premium_mode(enable boolean)
returns boolean
language plpgsql
security definer
as $$
begin
  update public.app_settings
  set premium_mode_enabled = enable,
      updated_at = now()
  where id = 1;
  return enable;
end;
$$;


-- 4. RPC: Suspend/Unsuspend Driver
create or replace function admin_toggle_suspension(target_driver_id uuid, suspend boolean)
returns boolean
language plpgsql
security definer
as $$
begin
  update public.users
  set is_suspended = suspend
  where id = target_driver_id;
  return suspend;
end;
$$;


-- 5. UPDATE MATCHING LOGIC (The Core Logic Change)
DROP FUNCTION IF EXISTS match_drivers_for_ride;

CREATE OR REPLACE FUNCTION match_drivers_for_ride(
  client_lat float,
  client_long float,
  radius_km int DEFAULT 5,
  limit_count int DEFAULT 10,
  excluded_driver_ids uuid[] DEFAULT '{}'
)
RETURNS TABLE (
  driver_id uuid,
  driver_name text,
  lat float,
  long float,
  distance_meters float,
  fcm_token text,
  rating float,
  car_model text,
  phone text
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
declare
  is_premium_active boolean;
begin
  -- Get the global setting
  select premium_mode_enabled into is_premium_active from public.app_settings limit 1;

  RETURN QUERY
  SELECT 
    u.id as driver_id,
    u.full_name as driver_name,
    u.current_lat as lat,
    u.current_lng as long,
    ST_Distance(
      u.location,
      ST_SetSRID(ST_MakePoint(client_long, client_lat), 4326)::geography
    ) as distance_meters,
    'dummy_token'::text as fcm_token,
    u.rating,
    u.car_model,
    u.phone
  FROM public.users u
  WHERE 
    u.role = 'driver' 
    AND u.is_online = true
    -- ALWAYS exclude manually suspended drivers
    AND u.is_suspended = false
    
    -- FREEMIUM LOGIC:
    -- If Premium Mode is ON, user MUST be verified.
    -- If Premium Mode is OFF, we verify NOTHING (allow all).
    AND (
      is_premium_active = false 
      OR 
      u.is_verified = true
    )

    -- Blacklist Logic (Keep existing)
    AND (excluded_driver_ids IS NULL OR NOT (u.id = ANY(excluded_driver_ids)))
    
    -- Spatial Logic
    AND ST_DWithin(
      u.location,
      ST_SetSRID(ST_MakePoint(client_long, client_lat), 4326)::geography,
      radius_km * 1000
    )
  ORDER BY distance_meters ASC
  LIMIT limit_count;
END;
$$;
